# fly.toml app configuration file generated for bamkfi-frontend-usdt-preview on 2024-07-12T04:05:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bamkfi-landing'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile.landing.prod'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
